/* ════════════════════════════════════════════════════════════
   Triple Beam Balance -- Internationalization (i18n) file
   ════════════════════════════════════════════════════════════
   Each language entry contains:
     name : the native name of the language (used in the dropdown)
     dir  : "ltr" or "rtl"
     unit : the unit suffix for grams (e.g. " g", " г", " غ", ...)
     t    : translation strings keyed by ID
   To add a new language, copy any block, change the code key
   (e.g. "fr"), translate the strings, and the simulation will
   pick it up automatically.
   ════════════════════════════════════════════════════════════ */
var tbbLang3932 = {
  /* ============================== ENGLISH ============================== */
  en: {
    name: "English",
    dir:  "ltr",
    unit: " g",
    t: {
      /* Toolbar buttons */
      btn_lm_off:        "LIGHT MODE",
      btn_lm_on:         "LIGHT MODE: ON",
      btn_nr_on:         "NARRATION: ON",
      btn_nr_off:        "NARRATION: OFF",
      btn_hc:            "HIGH CONTRAST",
      btn_fs_normal:     "FONT SIZE: NORMAL",
      btn_fs_lg:         "FONT SIZE: LARGE",
      btn_fs_xl:         "FONT SIZE: XL",
      lang_label:        "Language:",
      toolbar_label:     "Display options",
      /* SVG labels */
      svg_title:         "Triple Beam Balance",
      stage_label:       "Triple beam balance simulation",
      tare_beam_label:   "tare 225g",
      rear_beam_label:   "rear 100g",
      front_beam_label:  "front 10g",
      ctr_beam_label:    "ctr 500g",
      zero_lbl:          "zero",
      att_lbl:           "att.",
      /* Control labels */
      lbl_pan:           "Pan:",
      lbl_attachments:   "Attachments:",
      lbl_ctr_beam:      "▶ Center 500g:",
      lbl_rear_beam:     "▶ Rear 100g:",
      lbl_front_beam:    "▶ Front 10g:",
      lbl_tare_beam:     "▶ Tare 225g:",
      lbl_zero_adj:      "▶ Zero adj.:",
      lbl_beam_setting:  "Beam setting:",
      lbl_sample_mass:   "Sample mass:",
      lbl_ready:         "Ready?",
      /* Buttons */
      btn_add_mass:      "Add Mass",
      btn_add_container: "Add container",
      btn_mass_1kg:      "Mass 1 kg Attachment",
      btn_mass_500g:     "Mass 500g Attachment",
      btn_remove_mass:   "Remove mass",
      btn_reset_all:     "Reset all",
      btn_att_1kg:       "1 kg att. (rider: 295 g)",
      btn_att_500g:      "500 g att. (rider: 147.5 g)",
      btn_rezero:        "Re-zero",
      btn_submit:        "Submit answer",
      /* ARIA labels */
      aria_add_mass:      "Place the mass on the pan",
      aria_add_container: "Place a random container on the pan",
      aria_mass_1kg:      "Place a 1 kg attachment on the pan",
      aria_mass_500g:     "Place a 500 g attachment on the pan",
      aria_remove_mass:   "Remove the sample mass from the pan",
      aria_reset:         "Reset the balance to initial state",
      aria_att1:          "Toggle 1 kilogram attachment weight",
      aria_att5:          "Toggle 500 gram attachment weight",
      aria_ctr_slider:    "Center beam rider, 0 to 500 grams in 100 gram steps",
      aria_rear_slider:   "Rear beam rider, 0 to 100 grams in 10 gram steps",
      aria_front_slider:  "Front beam rider, 0 to 10 grams in 0.1 gram steps",
      aria_tare_slider:   "Tare beam, 0 to 225 grams. Cancels container weight. Not included in sample reading.",
      aria_zero_slider:   "Zero adjustment knob, fine balance correction",
      aria_rezero:        "Re-zero the balance at current beam settings",
      aria_submit:        "Submit your measurement and reveal the correct answer",
      aria_beam_setting:  "Current beam setting",
      aria_sample_mass:   "Calculated sample mass",
      aria_balance_img:   "Triple beam balance",
      /* Status messages */
      stat_balanced:     "BALANCED",
      stat_add_beam:     "add beam weight",
      stat_reduce_beam:  "reduce beam weight",
      stat_overload:     "over capacity",
      stat_at_zero:      "at zero",
      tag_overload:      "OVERLOAD",
      /* Narration messages -- placeholders use {var} */
      nar_intro:         "Triple Beam Balance simulation. The balance starts slightly off zero. Use the Zero adjustment slider to centre the pointer before weighing. Place a sample using the Add Mass button, then slide the beam riders from the largest beam to the smallest until the pointer aligns with zero. Submit your answer when ready.",
      nar_balanced:      "Balance is level. Beam setting: {beam} grams. Sample mass reading: {sample} grams.",
      nar_pan_heavy:     "Pan is heavy. Add more beam weight.",
      nar_beams_heavy:   "Beams are heavy. Reduce beam weight.",
      nar_mass_placed:   "Mass placed on the pan. Dial the beam riders from largest to smallest to find balance. Then submit your answer.",
      nar_att_placed:    "The {mass} kg attachment was placed on the pan. Dial the beam riders from largest to smallest to find balance. Then submit your answer.",
      nar_container_added:"Container placed on the pan. Its mass is {mass} g. Use the Tare slider to cancel the container weight, then add a sample.",
      nar_sample_removed:"Sample removed from pan.",
      nar_sample_removed_cont:"Sample removed. Container is still on the pan.",
      nar_reset:         "Balance reset. Use the Zero adjustment slider to centre the pointer, then place a sample.",
      nar_zeroed:        "Balance zeroed at current beam settings.",
      nar_att1_on:       "1 kilogram attachment hung on beam end. Beam side now counterbalances up to 1000 grams more on the pan.",
      nar_att1_off:      "1 kilogram attachment removed.",
      nar_att5_on:       "500 gram attachment hung on beam end. Beam side now counterbalances up to 500 grams more on the pan.",
      nar_att5_off:      "500 gram attachment removed.",
      nar_correct:       "Correct! Mass = {mass} g",
      nar_incorrect:     "Your reading: {reading} g. Actual mass: {correct} g",
      nar_lang_changed:  "Language changed to English.",
      /* Info panel */
      info_title:        "Triple Beam Balance",
      info_text:         "Capacity: 610 g (base) • Sensitivity/Readability: 0.1 g • Beams: Center 500g×100g • Rear 100g×10g • Front 10g×0.1g • Tare up to 225 g.<br><strong>To weigh:</strong> place a sample, then slide riders from largest beam to smallest until the pointer centres on 0. Use the <strong>Tare</strong> slider to cancel a container's weight before adding a sample. Use <strong>Zero adj.</strong> to correct a slight off-zero before weighing.",
      copyright:         "© Taha Mzoughi (2026)"
    }
  },

  /* ============================== FRENCH ============================== */
  fr: {
    name: "Français",
    dir:  "ltr",
    unit: " g",
    t: {
      btn_lm_off:        "MODE CLAIR",
      btn_lm_on:         "MODE CLAIR : ACTIVÉ",
      btn_nr_on:         "NARRATION : ACTIVÉE",
      btn_nr_off:        "NARRATION : DÉSACTIVÉE",
      btn_hc:            "CONTRASTE ÉLEVÉ",
      btn_fs_normal:     "TAILLE POLICE : NORMALE",
      btn_fs_lg:         "TAILLE POLICE : GRANDE",
      btn_fs_xl:         "TAILLE POLICE : XL",
      lang_label:        "Langue :",
      toolbar_label:     "Options d'affichage",
      svg_title:         "Balance à trois fléaux",
      stage_label:       "Simulation de balance à trois fléaux",
      tare_beam_label:   "tare 225g",
      rear_beam_label:   "arr. 100g",
      front_beam_label:  "av. 10g",
      ctr_beam_label:    "ctr 500g",
      zero_lbl:          "zéro",
      att_lbl:           "att.",
      lbl_pan:           "Plateau :",
      lbl_attachments:   "Accessoires :",
      lbl_ctr_beam:      "▶ Centre 500g :",
      lbl_rear_beam:     "▶ Arrière 100g :",
      lbl_front_beam:    "▶ Avant 10g :",
      lbl_tare_beam:     "▶ Tare 225g :",
      lbl_zero_adj:      "▶ Réglage zéro :",
      lbl_beam_setting:  "Lecture fléaux :",
      lbl_sample_mass:   "Masse échantillon :",
      lbl_ready:         "Prêt ?",
      btn_add_mass:      "Ajouter masse",
      btn_add_container: "Ajouter récipient",
      btn_mass_1kg:      "Masse 1 kg accessoire",
      btn_mass_500g:     "Masse 500g accessoire",
      btn_remove_mass:   "Retirer la masse",
      btn_reset_all:     "Tout réinitialiser",
      btn_att_1kg:       "Acc. 1 kg (curseur : 295 g)",
      btn_att_500g:      "Acc. 500 g (curseur : 147,5 g)",
      btn_rezero:        "Re-zéro",
      btn_submit:        "Valider la réponse",
      aria_add_mass:      "Placer la masse sur le plateau",
      aria_add_container: "Placer un récipient aléatoire sur le plateau",
      aria_mass_1kg:      "Placer un accessoire de 1 kg sur le plateau",
      aria_mass_500g:     "Placer un accessoire de 500 g sur le plateau",
      aria_remove_mass:   "Retirer la masse échantillon du plateau",
      aria_reset:         "Réinitialiser la balance",
      aria_att1:          "Activer/désactiver l'accessoire de 1 kilogramme",
      aria_att5:          "Activer/désactiver l'accessoire de 500 grammes",
      aria_ctr_slider:    "Curseur du fléau central, de 0 à 500 grammes par pas de 100 grammes",
      aria_rear_slider:   "Curseur du fléau arrière, de 0 à 100 grammes par pas de 10 grammes",
      aria_front_slider:  "Curseur du fléau avant, de 0 à 10 grammes par pas de 0,1 gramme",
      aria_tare_slider:   "Fléau de tare, de 0 à 225 grammes. Annule le poids du récipient.",
      aria_zero_slider:   "Bouton de réglage du zéro, correction fine de l'équilibre",
      aria_rezero:        "Remettre la balance à zéro avec les réglages actuels",
      aria_submit:        "Valider votre mesure et révéler la bonne réponse",
      aria_beam_setting:  "Réglage actuel des fléaux",
      aria_sample_mass:   "Masse calculée de l'échantillon",
      aria_balance_img:   "Balance à trois fléaux",
      stat_balanced:     "ÉQUILIBRÉE",
      stat_add_beam:     "ajouter du poids",
      stat_reduce_beam:  "réduire le poids",
      stat_overload:     "capacité dépassée",
      stat_at_zero:      "au zéro",
      tag_overload:      "SURCHARGE",
      nar_intro:         "Simulation de balance à trois fléaux. La balance commence légèrement décalée du zéro. Utilisez le curseur de réglage du zéro pour centrer le pointeur avant la pesée. Placez un échantillon avec le bouton Ajouter masse, puis faites glisser les curseurs du plus grand fléau au plus petit jusqu'à ce que le pointeur soit aligné avec le zéro. Validez votre réponse quand vous êtes prêt.",
      nar_balanced:      "Balance équilibrée. Réglage des fléaux : {beam} grammes. Masse de l'échantillon : {sample} grammes.",
      nar_pan_heavy:     "Le plateau est trop lourd. Ajoutez du poids aux fléaux.",
      nar_beams_heavy:   "Les fléaux sont trop lourds. Réduisez le poids des fléaux.",
      nar_mass_placed:   "Masse placée sur le plateau. Réglez les curseurs du plus grand au plus petit pour trouver l'équilibre, puis validez votre réponse.",
      nar_att_placed:    "L'accessoire de {mass} kg a été placé sur le plateau. Réglez les curseurs du plus grand au plus petit pour trouver l'équilibre.",
      nar_container_added:"Récipient placé sur le plateau. Sa masse est de {mass} g. Utilisez le curseur de tare pour annuler son poids, puis ajoutez un échantillon.",
      nar_sample_removed:"Échantillon retiré du plateau.",
      nar_sample_removed_cont:"Échantillon retiré. Le récipient est toujours sur le plateau.",
      nar_reset:         "Balance réinitialisée. Utilisez le curseur de réglage du zéro pour centrer le pointeur, puis placez un échantillon.",
      nar_zeroed:        "Balance remise à zéro aux réglages actuels.",
      nar_att1_on:       "Accessoire de 1 kilogramme accroché au fléau. Le côté fléaux compense maintenant jusqu'à 1000 grammes de plus sur le plateau.",
      nar_att1_off:      "Accessoire de 1 kilogramme retiré.",
      nar_att5_on:       "Accessoire de 500 grammes accroché au fléau. Le côté fléaux compense maintenant jusqu'à 500 grammes de plus sur le plateau.",
      nar_att5_off:      "Accessoire de 500 grammes retiré.",
      nar_correct:       "Correct ! Masse = {mass} g",
      nar_incorrect:     "Votre lecture : {reading} g. Masse réelle : {correct} g",
      nar_lang_changed:  "Langue changée en français.",
      info_title:        "Balance à trois fléaux",
      info_text:         "Capacité : 610 g (de base) • Sensibilité/Lisibilité : 0,1 g • Fléaux : Centre 500g×100g • Arrière 100g×10g • Avant 10g×0,1g • Tare jusqu'à 225 g.<br><strong>Pour peser :</strong> placez un échantillon, puis faites glisser les curseurs du plus grand fléau au plus petit jusqu'à ce que le pointeur soit centré sur 0. Utilisez le curseur <strong>Tare</strong> pour annuler le poids d'un récipient avant d'ajouter un échantillon. Utilisez <strong>Réglage zéro</strong> pour corriger un léger décalage du zéro.",
      copyright:         "© Taha Mzoughi (2026)"
    }
  },

  /* ============================== SPANISH ============================== */
  es: {
    name: "Español",
    dir:  "ltr",
    unit: " g",
    t: {
      btn_lm_off:        "MODO CLARO",
      btn_lm_on:         "MODO CLARO: ACTIVADO",
      btn_nr_on:         "NARRACIÓN: ACTIVADA",
      btn_nr_off:        "NARRACIÓN: DESACTIVADA",
      btn_hc:            "ALTO CONTRASTE",
      btn_fs_normal:     "TAMAÑO FUENTE: NORMAL",
      btn_fs_lg:         "TAMAÑO FUENTE: GRANDE",
      btn_fs_xl:         "TAMAÑO FUENTE: XL",
      lang_label:        "Idioma:",
      toolbar_label:     "Opciones de pantalla",
      svg_title:         "Balanza de tres brazos",
      stage_label:       "Simulación de balanza de tres brazos",
      tare_beam_label:   "tara 225g",
      rear_beam_label:   "tras. 100g",
      front_beam_label:  "del. 10g",
      ctr_beam_label:    "ctr 500g",
      zero_lbl:          "cero",
      att_lbl:           "acc.",
      lbl_pan:           "Plato:",
      lbl_attachments:   "Accesorios:",
      lbl_ctr_beam:      "▶ Centro 500g:",
      lbl_rear_beam:     "▶ Trasero 100g:",
      lbl_front_beam:    "▶ Delantero 10g:",
      lbl_tare_beam:     "▶ Tara 225g:",
      lbl_zero_adj:      "▶ Ajuste cero:",
      lbl_beam_setting:  "Lectura brazos:",
      lbl_sample_mass:   "Masa muestra:",
      lbl_ready:         "¿Listo?",
      btn_add_mass:      "Añadir masa",
      btn_add_container: "Añadir recipiente",
      btn_mass_1kg:      "Masa 1 kg accesorio",
      btn_mass_500g:     "Masa 500g accesorio",
      btn_remove_mass:   "Retirar masa",
      btn_reset_all:     "Reiniciar todo",
      btn_att_1kg:       "Acc. 1 kg (cursor: 295 g)",
      btn_att_500g:      "Acc. 500 g (cursor: 147,5 g)",
      btn_rezero:        "Re-cero",
      btn_submit:        "Enviar respuesta",
      aria_add_mass:      "Colocar la masa en el plato",
      aria_add_container: "Colocar un recipiente aleatorio en el plato",
      aria_mass_1kg:      "Colocar un accesorio de 1 kg en el plato",
      aria_mass_500g:     "Colocar un accesorio de 500 g en el plato",
      aria_remove_mass:   "Retirar la masa de muestra del plato",
      aria_reset:         "Reiniciar la balanza al estado inicial",
      aria_att1:          "Activar/desactivar el accesorio de 1 kilogramo",
      aria_att5:          "Activar/desactivar el accesorio de 500 gramos",
      aria_ctr_slider:    "Cursor del brazo central, de 0 a 500 gramos en pasos de 100 gramos",
      aria_rear_slider:   "Cursor del brazo trasero, de 0 a 100 gramos en pasos de 10 gramos",
      aria_front_slider:  "Cursor del brazo delantero, de 0 a 10 gramos en pasos de 0,1 gramo",
      aria_tare_slider:   "Brazo de tara, de 0 a 225 gramos. Cancela el peso del recipiente.",
      aria_zero_slider:   "Perilla de ajuste de cero, corrección fina del equilibrio",
      aria_rezero:        "Reajustar la balanza a cero con la configuración actual",
      aria_submit:        "Enviar su medición y revelar la respuesta correcta",
      aria_beam_setting:  "Configuración actual de los brazos",
      aria_sample_mass:   "Masa calculada de la muestra",
      aria_balance_img:   "Balanza de tres brazos",
      stat_balanced:     "EQUILIBRADA",
      stat_add_beam:     "añadir peso",
      stat_reduce_beam:  "reducir peso",
      stat_overload:     "capacidad excedida",
      stat_at_zero:      "en cero",
      tag_overload:      "SOBRECARGA",
      nar_intro:         "Simulación de balanza de tres brazos. La balanza comienza ligeramente desviada del cero. Use el cursor de ajuste de cero para centrar el puntero antes de pesar. Coloque una muestra usando el botón Añadir masa, luego deslice los cursores del brazo más grande al más pequeño hasta que el puntero esté alineado con el cero. Envíe su respuesta cuando esté listo.",
      nar_balanced:      "Balanza equilibrada. Configuración brazos: {beam} gramos. Masa de la muestra: {sample} gramos.",
      nar_pan_heavy:     "El plato está pesado. Añada más peso a los brazos.",
      nar_beams_heavy:   "Los brazos están pesados. Reduzca el peso de los brazos.",
      nar_mass_placed:   "Masa colocada en el plato. Ajuste los cursores del más grande al más pequeño para encontrar el equilibrio. Luego envíe su respuesta.",
      nar_att_placed:    "El accesorio de {mass} kg fue colocado en el plato. Ajuste los cursores del más grande al más pequeño para encontrar el equilibrio.",
      nar_container_added:"Recipiente colocado en el plato. Su masa es de {mass} g. Use el cursor de tara para cancelar el peso del recipiente, luego añada una muestra.",
      nar_sample_removed:"Muestra retirada del plato.",
      nar_sample_removed_cont:"Muestra retirada. El recipiente sigue en el plato.",
      nar_reset:         "Balanza reiniciada. Use el cursor de ajuste de cero para centrar el puntero, luego coloque una muestra.",
      nar_zeroed:        "Balanza puesta a cero en la configuración actual.",
      nar_att1_on:       "Accesorio de 1 kilogramo colgado en el extremo del brazo. El lado de los brazos ahora contrarresta hasta 1000 gramos más en el plato.",
      nar_att1_off:      "Accesorio de 1 kilogramo retirado.",
      nar_att5_on:       "Accesorio de 500 gramos colgado en el extremo del brazo. El lado de los brazos ahora contrarresta hasta 500 gramos más en el plato.",
      nar_att5_off:      "Accesorio de 500 gramos retirado.",
      nar_correct:       "¡Correcto! Masa = {mass} g",
      nar_incorrect:     "Su lectura: {reading} g. Masa real: {correct} g",
      nar_lang_changed:  "Idioma cambiado a español.",
      info_title:        "Balanza de tres brazos",
      info_text:         "Capacidad: 610 g (base) • Sensibilidad/Legibilidad: 0,1 g • Brazos: Centro 500g×100g • Trasero 100g×10g • Delantero 10g×0,1g • Tara hasta 225 g.<br><strong>Para pesar:</strong> coloque una muestra, luego deslice los cursores del brazo más grande al más pequeño hasta que el puntero se centre en 0. Use el cursor <strong>Tara</strong> para cancelar el peso de un recipiente antes de añadir una muestra. Use <strong>Ajuste cero</strong> para corregir un ligero desvío del cero antes de pesar.",
      copyright:         "© Taha Mzoughi (2026)"
    }
  },

  /* ============================== GERMAN ============================== */
  de: {
    name: "Deutsch",
    dir:  "ltr",
    unit: " g",
    t: {
      btn_lm_off:        "HELLER MODUS",
      btn_lm_on:         "HELLER MODUS: AN",
      btn_nr_on:         "ERZÄHLUNG: AN",
      btn_nr_off:        "ERZÄHLUNG: AUS",
      btn_hc:            "HOHER KONTRAST",
      btn_fs_normal:     "SCHRIFTGRÖSSE: NORMAL",
      btn_fs_lg:         "SCHRIFTGRÖSSE: GROSS",
      btn_fs_xl:         "SCHRIFTGRÖSSE: XL",
      lang_label:        "Sprache:",
      toolbar_label:     "Anzeigeoptionen",
      svg_title:         "Dreibalkenwaage",
      stage_label:       "Dreibalkenwaagen-Simulation",
      tare_beam_label:   "Tara 225g",
      rear_beam_label:   "hint. 100g",
      front_beam_label:  "vord. 10g",
      ctr_beam_label:    "mit. 500g",
      zero_lbl:          "Null",
      att_lbl:           "Anh.",
      lbl_pan:           "Schale:",
      lbl_attachments:   "Anhänge:",
      lbl_ctr_beam:      "▶ Mitte 500g:",
      lbl_rear_beam:     "▶ Hinten 100g:",
      lbl_front_beam:    "▶ Vorne 10g:",
      lbl_tare_beam:     "▶ Tara 225g:",
      lbl_zero_adj:      "▶ Null-Einstellung:",
      lbl_beam_setting:  "Balkenwert:",
      lbl_sample_mass:   "Probenmasse:",
      lbl_ready:         "Bereit?",
      btn_add_mass:      "Masse hinzufügen",
      btn_add_container: "Behälter hinzufügen",
      btn_mass_1kg:      "1 kg Anhang",
      btn_mass_500g:     "500 g Anhang",
      btn_remove_mass:   "Masse entfernen",
      btn_reset_all:     "Alles zurücksetzen",
      btn_att_1kg:       "1 kg Anh. (Reiter: 295 g)",
      btn_att_500g:      "500 g Anh. (Reiter: 147,5 g)",
      btn_rezero:        "Null setzen",
      btn_submit:        "Antwort senden",
      aria_add_mass:      "Masse auf die Schale legen",
      aria_add_container: "Einen zufälligen Behälter auf die Schale legen",
      aria_mass_1kg:      "Einen 1-kg-Anhang auf die Schale legen",
      aria_mass_500g:     "Einen 500-g-Anhang auf die Schale legen",
      aria_remove_mass:   "Probenmasse von der Schale entfernen",
      aria_reset:         "Waage in den Anfangszustand zurücksetzen",
      aria_att1:          "1-Kilogramm-Anhang umschalten",
      aria_att5:          "500-Gramm-Anhang umschalten",
      aria_ctr_slider:    "Mittlerer Balkenreiter, 0 bis 500 Gramm in 100-Gramm-Schritten",
      aria_rear_slider:   "Hinterer Balkenreiter, 0 bis 100 Gramm in 10-Gramm-Schritten",
      aria_front_slider:  "Vorderer Balkenreiter, 0 bis 10 Gramm in 0,1-Gramm-Schritten",
      aria_tare_slider:   "Tarabalken, 0 bis 225 Gramm. Hebt das Behältergewicht auf.",
      aria_zero_slider:   "Null-Einstellknopf, Feinabgleich der Balance",
      aria_rezero:        "Waage mit aktuellen Balkeneinstellungen auf Null setzen",
      aria_submit:        "Messung absenden und korrekte Antwort anzeigen",
      aria_beam_setting:  "Aktuelle Balkeneinstellung",
      aria_sample_mass:   "Berechnete Probenmasse",
      aria_balance_img:   "Dreibalkenwaage",
      stat_balanced:     "AUSGEGLICHEN",
      stat_add_beam:     "Balkengewicht erhöhen",
      stat_reduce_beam:  "Balkengewicht verringern",
      stat_overload:     "Kapazität überschritten",
      stat_at_zero:      "auf null",
      tag_overload:      "ÜBERLAST",
      nar_intro:         "Dreibalkenwaagen-Simulation. Die Waage startet leicht außerhalb der Null. Verwenden Sie den Null-Einstellschieber, um den Zeiger vor dem Wiegen zu zentrieren. Legen Sie eine Probe mit dem Knopf Masse hinzufügen auf, dann verschieben Sie die Balkenreiter vom größten Balken zum kleinsten, bis der Zeiger auf null steht. Senden Sie Ihre Antwort ab, wenn Sie fertig sind.",
      nar_balanced:      "Waage ist ausgeglichen. Balkeneinstellung: {beam} Gramm. Probenmasse: {sample} Gramm.",
      nar_pan_heavy:     "Schale ist zu schwer. Mehr Balkengewicht hinzufügen.",
      nar_beams_heavy:   "Balken sind zu schwer. Balkengewicht verringern.",
      nar_mass_placed:   "Masse auf die Schale gelegt. Stellen Sie die Balkenreiter vom größten zum kleinsten ein, um das Gleichgewicht zu finden. Dann senden Sie Ihre Antwort ab.",
      nar_att_placed:    "Der {mass} kg Anhang wurde auf die Schale gelegt. Stellen Sie die Balkenreiter vom größten zum kleinsten ein, um das Gleichgewicht zu finden.",
      nar_container_added:"Behälter auf die Schale gelegt. Seine Masse beträgt {mass} g. Verwenden Sie den Tara-Schieber, um das Behältergewicht aufzuheben, dann fügen Sie eine Probe hinzu.",
      nar_sample_removed:"Probe von der Schale entfernt.",
      nar_sample_removed_cont:"Probe entfernt. Der Behälter befindet sich noch auf der Schale.",
      nar_reset:         "Waage zurückgesetzt. Verwenden Sie den Null-Einstellschieber, um den Zeiger zu zentrieren, dann legen Sie eine Probe auf.",
      nar_zeroed:        "Waage mit aktuellen Balkeneinstellungen auf null gesetzt.",
      nar_att1_on:       "1-Kilogramm-Anhang am Balkenende aufgehängt. Die Balkenseite gleicht jetzt bis zu 1000 Gramm mehr auf der Schale aus.",
      nar_att1_off:      "1-Kilogramm-Anhang entfernt.",
      nar_att5_on:       "500-Gramm-Anhang am Balkenende aufgehängt. Die Balkenseite gleicht jetzt bis zu 500 Gramm mehr auf der Schale aus.",
      nar_att5_off:      "500-Gramm-Anhang entfernt.",
      nar_correct:       "Richtig! Masse = {mass} g",
      nar_incorrect:     "Ihre Ablesung: {reading} g. Tatsächliche Masse: {correct} g",
      nar_lang_changed:  "Sprache auf Deutsch geändert.",
      info_title:        "Dreibalkenwaage",
      info_text:         "Kapazität: 610 g (Basis) • Empfindlichkeit/Ablesbarkeit: 0,1 g • Balken: Mitte 500g×100g • Hinten 100g×10g • Vorne 10g×0,1g • Tara bis 225 g.<br><strong>Zum Wiegen:</strong> Probe auflegen, dann Reiter vom größten zum kleinsten Balken schieben, bis der Zeiger auf 0 steht. Verwenden Sie den <strong>Tara</strong>-Schieber, um das Gewicht eines Behälters aufzuheben. Verwenden Sie <strong>Null-Einstellung</strong>, um eine leichte Abweichung vor dem Wiegen zu korrigieren.",
      copyright:         "© Taha Mzoughi (2026)"
    }
  },

  /* ============================== ARABIC (RTL) ============================== */
  ar: {
    name: "العربية",
    dir:  "rtl",
    unit: " غ",
    t: {
      btn_lm_off:        "الوضع الفاتح",
      btn_lm_on:         "الوضع الفاتح: مُفعّل",
      btn_nr_on:         "السرد: مُفعّل",
      btn_nr_off:        "السرد: مُعطّل",
      btn_hc:            "تباين عالٍ",
      btn_fs_normal:     "حجم الخط: عادي",
      btn_fs_lg:         "حجم الخط: كبير",
      btn_fs_xl:         "حجم الخط: كبير جداً",
      lang_label:        "اللغة:",
      toolbar_label:     "خيارات العرض",
      svg_title:         "ميزان ثلاثي الأذرع",
      stage_label:       "محاكاة الميزان الثلاثي الأذرع",
      tare_beam_label:   "تار 225غ",
      rear_beam_label:   "خلفي 100غ",
      front_beam_label:  "أمامي 10غ",
      ctr_beam_label:    "وسط 500غ",
      zero_lbl:          "صفر",
      att_lbl:           "ملح.",
      lbl_pan:           "الكفة:",
      lbl_attachments:   "الملحقات:",
      lbl_ctr_beam:      "◀ الذراع الأوسط 500غ:",
      lbl_rear_beam:     "◀ الذراع الخلفي 100غ:",
      lbl_front_beam:    "◀ الذراع الأمامي 10غ:",
      lbl_tare_beam:     "◀ ذراع التار 225غ:",
      lbl_zero_adj:      "◀ ضبط الصفر:",
      lbl_beam_setting:  "إعداد الأذرع:",
      lbl_sample_mass:   "كتلة العينة:",
      lbl_ready:         "جاهز؟",
      btn_add_mass:      "إضافة كتلة",
      btn_add_container: "إضافة وعاء",
      btn_mass_1kg:      "ملحق كتلة 1 كغ",
      btn_mass_500g:     "ملحق كتلة 500 غ",
      btn_remove_mass:   "إزالة الكتلة",
      btn_reset_all:     "إعادة تعيين الكل",
      btn_att_1kg:       "ملحق 1 كغ (مؤشر: 295 غ)",
      btn_att_500g:      "ملحق 500 غ (مؤشر: 147.5 غ)",
      btn_rezero:        "إعادة الصفر",
      btn_submit:        "إرسال الإجابة",
      aria_add_mass:      "ضع الكتلة على الكفة",
      aria_add_container: "ضع وعاء عشوائي على الكفة",
      aria_mass_1kg:      "ضع ملحق 1 كغ على الكفة",
      aria_mass_500g:     "ضع ملحق 500 غ على الكفة",
      aria_remove_mass:   "أزل كتلة العينة من الكفة",
      aria_reset:         "أعد ضبط الميزان إلى الحالة الأولية",
      aria_att1:          "تبديل ملحق الكيلوغرام الواحد",
      aria_att5:          "تبديل ملحق 500 غرام",
      aria_ctr_slider:    "مؤشر الذراع الأوسط، من 0 إلى 500 غرام بخطوات 100 غرام",
      aria_rear_slider:   "مؤشر الذراع الخلفي، من 0 إلى 100 غرام بخطوات 10 غرام",
      aria_front_slider:  "مؤشر الذراع الأمامي، من 0 إلى 10 غرامات بخطوات 0.1 غرام",
      aria_tare_slider:   "ذراع التار، من 0 إلى 225 غرام. يلغي وزن الوعاء.",
      aria_zero_slider:   "مقبض ضبط الصفر، تصحيح دقيق للتوازن",
      aria_rezero:        "أعد ضبط الميزان إلى الصفر بالإعدادات الحالية",
      aria_submit:        "أرسل قياسك واكشف الإجابة الصحيحة",
      aria_beam_setting:  "إعداد الأذرع الحالي",
      aria_sample_mass:   "الكتلة المحسوبة للعينة",
      aria_balance_img:   "ميزان ثلاثي الأذرع",
      stat_balanced:     "متوازن",
      stat_add_beam:     "أضف وزناً للأذرع",
      stat_reduce_beam:  "قلل وزن الأذرع",
      stat_overload:     "تجاوز السعة",
      stat_at_zero:      "عند الصفر",
      tag_overload:      "حمل زائد",
      nar_intro:         "محاكاة الميزان الثلاثي الأذرع. يبدأ الميزان منحرفاً قليلاً عن الصفر. استخدم منزلق ضبط الصفر لتوسيط المؤشر قبل الوزن. ضع عينة باستخدام زر إضافة كتلة، ثم حرّك مؤشرات الأذرع من الأكبر إلى الأصغر حتى يتطابق المؤشر مع الصفر. أرسل إجابتك عندما تكون جاهزاً.",
      nar_balanced:      "الميزان متوازن. إعداد الأذرع: {beam} غرام. كتلة العينة: {sample} غرام.",
      nar_pan_heavy:     "الكفة ثقيلة. أضف المزيد من وزن الأذرع.",
      nar_beams_heavy:   "الأذرع ثقيلة. قلل من وزن الأذرع.",
      nar_mass_placed:   "تم وضع الكتلة على الكفة. اضبط مؤشرات الأذرع من الأكبر إلى الأصغر لإيجاد التوازن. ثم أرسل إجابتك.",
      nar_att_placed:    "تم وضع ملحق {mass} كغ على الكفة. اضبط مؤشرات الأذرع من الأكبر إلى الأصغر لإيجاد التوازن.",
      nar_container_added:"تم وضع وعاء على الكفة. كتلته {mass} غ. استخدم منزلق التار لإلغاء وزن الوعاء، ثم أضف عينة.",
      nar_sample_removed:"تمت إزالة العينة من الكفة.",
      nar_sample_removed_cont:"تمت إزالة العينة. لا يزال الوعاء على الكفة.",
      nar_reset:         "تمت إعادة ضبط الميزان. استخدم منزلق ضبط الصفر لتوسيط المؤشر، ثم ضع عينة.",
      nar_zeroed:        "تمت إعادة الميزان إلى الصفر بالإعدادات الحالية.",
      nar_att1_on:       "تم تعليق ملحق 1 كيلوغرام على طرف الذراع. جانب الأذرع يوازن الآن حتى 1000 غرام إضافية على الكفة.",
      nar_att1_off:      "تمت إزالة ملحق 1 كيلوغرام.",
      nar_att5_on:       "تم تعليق ملحق 500 غرام على طرف الذراع. جانب الأذرع يوازن الآن حتى 500 غرام إضافية على الكفة.",
      nar_att5_off:      "تمت إزالة ملحق 500 غرام.",
      nar_correct:       "صحيح! الكتلة = {mass} غ",
      nar_incorrect:     "قراءتك: {reading} غ. الكتلة الفعلية: {correct} غ",
      nar_lang_changed:  "تم تغيير اللغة إلى العربية.",
      info_title:        "الميزان ثلاثي الأذرع",
      info_text:         "السعة: 610 غ (أساسية) • الحساسية/قابلية القراءة: 0.1 غ • الأذرع: وسطي 500غ×100غ • خلفي 100غ×10غ • أمامي 10غ×0.1غ • تار حتى 225 غ.<br><strong>للوزن:</strong> ضع عينة، ثم حرّك المؤشرات من الذراع الأكبر إلى الأصغر حتى يتوسط المؤشر على 0. استخدم منزلق <strong>التار</strong> لإلغاء وزن الوعاء قبل إضافة عينة. استخدم <strong>ضبط الصفر</strong> لتصحيح انحراف طفيف قبل الوزن.",
      copyright:         "© طه مزوغي (2026)"
    }
  },

  /* ============================== HEBREW (RTL) ============================== */
  he: {
    name: "עברית",
    dir:  "rtl",
    unit: " ג",
    t: {
      btn_lm_off:        "מצב בהיר",
      btn_lm_on:         "מצב בהיר: פעיל",
      btn_nr_on:         "קריינות: פעילה",
      btn_nr_off:        "קריינות: כבויה",
      btn_hc:            "ניגודיות גבוהה",
      btn_fs_normal:     "גודל גופן: רגיל",
      btn_fs_lg:         "גודל גופן: גדול",
      btn_fs_xl:         "גודל גופן: ענק",
      lang_label:        "שפה:",
      toolbar_label:     "אפשרויות תצוגה",
      svg_title:         "מאזניים תלת-זרועיים",
      stage_label:       "סימולציה של מאזניים תלת-זרועיים",
      tare_beam_label:   "טרה 225ג",
      rear_beam_label:   "אחורי 100ג",
      front_beam_label:  "קדמי 10ג",
      ctr_beam_label:    "אמצעי 500ג",
      zero_lbl:          "אפס",
      att_lbl:           "תוס.",
      lbl_pan:           "כף:",
      lbl_attachments:   "תוספים:",
      lbl_ctr_beam:      "◀ אמצעי 500ג:",
      lbl_rear_beam:     "◀ אחורי 100ג:",
      lbl_front_beam:    "◀ קדמי 10ג:",
      lbl_tare_beam:     "◀ טרה 225ג:",
      lbl_zero_adj:      "◀ כיוון אפס:",
      lbl_beam_setting:  "ערך זרועות:",
      lbl_sample_mass:   "מסת דגימה:",
      lbl_ready:         "מוכן?",
      btn_add_mass:      "הוסף מסה",
      btn_add_container: "הוסף מיכל",
      btn_mass_1kg:      "תוסף מסה 1 ק״ג",
      btn_mass_500g:     "תוסף מסה 500 ג",
      btn_remove_mass:   "הסר מסה",
      btn_reset_all:     "אפס הכל",
      btn_att_1kg:       "תוס׳ 1 ק״ג (סמן: 295 ג)",
      btn_att_500g:      "תוס׳ 500 ג (סמן: 147.5 ג)",
      btn_rezero:        "אפס מחדש",
      btn_submit:        "שלח תשובה",
      aria_add_mass:      "הנח את המסה על הכף",
      aria_add_container: "הנח מיכל אקראי על הכף",
      aria_mass_1kg:      "הנח תוסף 1 ק״ג על הכף",
      aria_mass_500g:     "הנח תוסף 500 ג על הכף",
      aria_remove_mass:   "הסר את מסת הדגימה מהכף",
      aria_reset:         "אפס את המאזניים למצב התחלתי",
      aria_att1:          "החלף תוסף קילוגרם",
      aria_att5:          "החלף תוסף 500 גרם",
      aria_ctr_slider:    "סמן זרוע אמצעית, 0 עד 500 גרם בצעדים של 100 גרם",
      aria_rear_slider:   "סמן זרוע אחורית, 0 עד 100 גרם בצעדים של 10 גרם",
      aria_front_slider:  "סמן זרוע קדמית, 0 עד 10 גרם בצעדים של 0.1 גרם",
      aria_tare_slider:   "זרוע טרה, 0 עד 225 גרם. מבטלת את משקל המיכל.",
      aria_zero_slider:   "כפתור כיוון אפס, תיקון איזון עדין",
      aria_rezero:        "אפס את המאזניים מחדש בהגדרות הנוכחיות",
      aria_submit:        "שלח את המדידה וגלה את התשובה הנכונה",
      aria_beam_setting:  "הגדרת זרועות נוכחית",
      aria_sample_mass:   "מסת הדגימה המחושבת",
      aria_balance_img:   "מאזניים תלת-זרועיים",
      stat_balanced:     "מאוזן",
      stat_add_beam:     "הוסף משקל לזרועות",
      stat_reduce_beam:  "הפחת משקל מהזרועות",
      stat_overload:     "מעבר לקיבולת",
      stat_at_zero:      "באפס",
      tag_overload:      "עומס יתר",
      nar_intro:         "סימולציה של מאזניים תלת-זרועיים. המאזניים מתחילים מעט מחוץ לאפס. השתמש בסמן כיוון האפס למרכז את המחוון לפני השקילה. הנח דגימה באמצעות כפתור הוסף מסה, ואז החלק את סמני הזרועות מהזרוע הגדולה לקטנה עד שהמחוון יתיישר עם האפס. שלח את התשובה כשתהיה מוכן.",
      nar_balanced:      "המאזניים מאוזנים. הגדרת זרועות: {beam} גרם. מסת הדגימה: {sample} גרם.",
      nar_pan_heavy:     "הכף כבדה. הוסף משקל לזרועות.",
      nar_beams_heavy:   "הזרועות כבדות. הפחת משקל מהזרועות.",
      nar_mass_placed:   "מסה הונחה על הכף. כוון את הסמנים מהגדול לקטן למציאת איזון, ואז שלח את התשובה.",
      nar_att_placed:    "תוסף {mass} ק״ג הונח על הכף. כוון את הסמנים מהגדול לקטן למציאת איזון.",
      nar_container_added:"מיכל הונח על הכף. מסתו {mass} ג. השתמש בסמן הטרה לביטול משקל המיכל, ואז הוסף דגימה.",
      nar_sample_removed:"הדגימה הוסרה מהכף.",
      nar_sample_removed_cont:"הדגימה הוסרה. המיכל עדיין על הכף.",
      nar_reset:         "המאזניים אופסו. השתמש בסמן כיוון האפס למרכז את המחוון, ואז הנח דגימה.",
      nar_zeroed:        "המאזניים אופסו בהגדרות הנוכחיות.",
      nar_att1_on:       "תוסף קילוגרם נתלה בקצה הזרוע. צד הזרועות מאזן כעת עד 1000 גרם נוספים על הכף.",
      nar_att1_off:      "תוסף קילוגרם הוסר.",
      nar_att5_on:       "תוסף 500 גרם נתלה בקצה הזרוע. צד הזרועות מאזן כעת עד 500 גרם נוספים על הכף.",
      nar_att5_off:      "תוסף 500 גרם הוסר.",
      nar_correct:       "נכון! מסה = {mass} ג",
      nar_incorrect:     "הקריאה שלך: {reading} ג. המסה האמיתית: {correct} ג",
      nar_lang_changed:  "השפה שונתה לעברית.",
      info_title:        "מאזניים תלת-זרועיים",
      info_text:         "קיבולת: 610 ג (בסיס) • רגישות/קריאות: 0.1 ג • זרועות: אמצעית 500ג×100ג • אחורית 100ג×10ג • קדמית 10ג×0.1ג • טרה עד 225 ג.<br><strong>לשקילה:</strong> הנח דגימה, החלק את הסמנים מהזרוע הגדולה לקטנה עד שהמחוון מתמרכז על 0. השתמש בסמן <strong>טרה</strong> לביטול משקל מיכל. השתמש ב<strong>כיוון אפס</strong> לתיקון סטייה קלה לפני שקילה.",
      copyright:         "© Taha Mzoughi (2026)"
    }
  },

  /* ============================== CHINESE (Simplified) ============================== */
  zh: {
    name: "中文",
    dir:  "ltr",
    unit: " 克",
    t: {
      btn_lm_off:        "浅色模式",
      btn_lm_on:         "浅色模式：开",
      btn_nr_on:         "旁白：开",
      btn_nr_off:        "旁白：关",
      btn_hc:            "高对比度",
      btn_fs_normal:     "字号：普通",
      btn_fs_lg:         "字号：大",
      btn_fs_xl:         "字号：特大",
      lang_label:        "语言：",
      toolbar_label:     "显示选项",
      svg_title:         "三梁天平",
      stage_label:       "三梁天平模拟",
      tare_beam_label:   "去皮 225克",
      rear_beam_label:   "后 100克",
      front_beam_label:  "前 10克",
      ctr_beam_label:    "中 500克",
      zero_lbl:          "零",
      att_lbl:           "附件",
      lbl_pan:           "托盘：",
      lbl_attachments:   "附件：",
      lbl_ctr_beam:      "▶ 中梁 500克：",
      lbl_rear_beam:     "▶ 后梁 100克：",
      lbl_front_beam:    "▶ 前梁 10克：",
      lbl_tare_beam:     "▶ 去皮 225克：",
      lbl_zero_adj:      "▶ 调零：",
      lbl_beam_setting:  "梁读数：",
      lbl_sample_mass:   "样品质量：",
      lbl_ready:         "准备好了？",
      btn_add_mass:      "添加质量",
      btn_add_container: "添加容器",
      btn_mass_1kg:      "1 千克附件质量",
      btn_mass_500g:     "500 克附件质量",
      btn_remove_mass:   "移除质量",
      btn_reset_all:     "全部重置",
      btn_att_1kg:       "1 千克附件（游码：295 克）",
      btn_att_500g:      "500 克附件（游码：147.5 克）",
      btn_rezero:        "重新归零",
      btn_submit:        "提交答案",
      aria_add_mass:      "将质量放在托盘上",
      aria_add_container: "在托盘上放置随机容器",
      aria_mass_1kg:      "在托盘上放置 1 千克附件",
      aria_mass_500g:     "在托盘上放置 500 克附件",
      aria_remove_mass:   "从托盘上移除样品质量",
      aria_reset:         "将天平重置为初始状态",
      aria_att1:          "切换 1 千克附件重",
      aria_att5:          "切换 500 克附件重",
      aria_ctr_slider:    "中梁游码，0 到 500 克，每步 100 克",
      aria_rear_slider:   "后梁游码，0 到 100 克，每步 10 克",
      aria_front_slider:  "前梁游码，0 到 10 克，每步 0.1 克",
      aria_tare_slider:   "去皮梁，0 到 225 克。抵消容器重量。",
      aria_zero_slider:   "调零旋钮，精细平衡校正",
      aria_rezero:        "在当前梁设置下重新归零天平",
      aria_submit:        "提交测量并显示正确答案",
      aria_beam_setting:  "当前梁设置",
      aria_sample_mass:   "计算的样品质量",
      aria_balance_img:   "三梁天平",
      stat_balanced:     "已平衡",
      stat_add_beam:     "增加梁重",
      stat_reduce_beam:  "减少梁重",
      stat_overload:     "超过容量",
      stat_at_zero:      "在零位",
      tag_overload:      "超载",
      nar_intro:         "三梁天平模拟。天平开始时略微偏离零。在称重前使用调零滑块将指针居中。使用添加质量按钮放置样品，然后将梁游码从最大梁滑到最小梁，直到指针与零对齐。准备就绪后提交答案。",
      nar_balanced:      "天平已平衡。梁设置：{beam} 克。样品质量读数：{sample} 克。",
      nar_pan_heavy:     "托盘较重。增加梁重。",
      nar_beams_heavy:   "梁较重。减少梁重。",
      nar_mass_placed:   "质量已放在托盘上。从最大到最小调节梁游码找到平衡，然后提交答案。",
      nar_att_placed:    "{mass} 千克附件已放在托盘上。从最大到最小调节梁游码找到平衡。",
      nar_container_added:"容器已放在托盘上。其质量为 {mass} 克。使用去皮滑块抵消容器重量，然后添加样品。",
      nar_sample_removed:"样品已从托盘上移除。",
      nar_sample_removed_cont:"样品已移除。容器仍在托盘上。",
      nar_reset:         "天平已重置。使用调零滑块将指针居中，然后放置样品。",
      nar_zeroed:        "天平已在当前梁设置下归零。",
      nar_att1_on:       "1 千克附件已挂在梁端。梁侧现在可以多平衡托盘上 1000 克的重量。",
      nar_att1_off:      "1 千克附件已移除。",
      nar_att5_on:       "500 克附件已挂在梁端。梁侧现在可以多平衡托盘上 500 克的重量。",
      nar_att5_off:      "500 克附件已移除。",
      nar_correct:       "正确！质量 = {mass} 克",
      nar_incorrect:     "你的读数：{reading} 克。实际质量：{correct} 克",
      nar_lang_changed:  "语言已切换为中文。",
      info_title:        "三梁天平",
      info_text:         "容量：610 克（基本）• 灵敏度/可读性：0.1 克 • 梁：中梁 500克×100克 • 后梁 100克×10克 • 前梁 10克×0.1克 • 去皮至 225 克。<br><strong>称重方法：</strong>放置样品，然后将游码从最大梁滑到最小梁，直到指针在 0 上居中。在添加样品前使用<strong>去皮</strong>滑块抵消容器重量。使用<strong>调零</strong>在称重前校正轻微的零位偏差。",
      copyright:         "© Taha Mzoughi (2026)"
    }
  },

  /* ============================== JAPANESE ============================== */
  ja: {
    name: "日本語",
    dir:  "ltr",
    unit: " g",
    t: {
      btn_lm_off:        "ライトモード",
      btn_lm_on:         "ライトモード:オン",
      btn_nr_on:         "ナレーション:オン",
      btn_nr_off:        "ナレーション:オフ",
      btn_hc:            "ハイコントラスト",
      btn_fs_normal:     "フォントサイズ:標準",
      btn_fs_lg:         "フォントサイズ:大",
      btn_fs_xl:         "フォントサイズ:特大",
      lang_label:        "言語:",
      toolbar_label:     "表示オプション",
      svg_title:         "三連天秤",
      stage_label:       "三連天秤シミュレーション",
      tare_beam_label:   "風袋 225g",
      rear_beam_label:   "後 100g",
      front_beam_label:  "前 10g",
      ctr_beam_label:    "中 500g",
      zero_lbl:          "零",
      att_lbl:           "付属",
      lbl_pan:           "皿:",
      lbl_attachments:   "付属品:",
      lbl_ctr_beam:      "▶ 中央梁 500g:",
      lbl_rear_beam:     "▶ 後部梁 100g:",
      lbl_front_beam:    "▶ 前部梁 10g:",
      lbl_tare_beam:     "▶ 風袋梁 225g:",
      lbl_zero_adj:      "▶ ゼロ調整:",
      lbl_beam_setting:  "梁の設定:",
      lbl_sample_mass:   "試料質量:",
      lbl_ready:         "準備完了?",
      btn_add_mass:      "質量を追加",
      btn_add_container: "容器を追加",
      btn_mass_1kg:      "1 kg 付属質量",
      btn_mass_500g:     "500g 付属質量",
      btn_remove_mass:   "質量を取り除く",
      btn_reset_all:     "すべてリセット",
      btn_att_1kg:       "1 kg 付属(おもり: 295g)",
      btn_att_500g:      "500g 付属(おもり: 147.5g)",
      btn_rezero:        "再ゼロ",
      btn_submit:        "回答を送信",
      aria_add_mass:      "皿に質量を置く",
      aria_add_container: "皿にランダムな容器を置く",
      aria_mass_1kg:      "皿に 1 kg の付属品を置く",
      aria_mass_500g:     "皿に 500g の付属品を置く",
      aria_remove_mass:   "皿から試料質量を取り除く",
      aria_reset:         "天秤を初期状態にリセットする",
      aria_att1:          "1 キログラム付属品の重さを切り替える",
      aria_att5:          "500 グラム付属品の重さを切り替える",
      aria_ctr_slider:    "中央梁のおもり、0 から 500 グラム、100 グラム刻み",
      aria_rear_slider:   "後部梁のおもり、0 から 100 グラム、10 グラム刻み",
      aria_front_slider:  "前部梁のおもり、0 から 10 グラム、0.1 グラム刻み",
      aria_tare_slider:   "風袋梁、0 から 225 グラム。容器の重さを相殺します。",
      aria_zero_slider:   "ゼロ調整ノブ、微細な釣り合い補正",
      aria_rezero:        "現在の梁設定で天秤をゼロに戻す",
      aria_submit:        "測定値を送信し正解を表示する",
      aria_beam_setting:  "現在の梁設定",
      aria_sample_mass:   "計算された試料質量",
      aria_balance_img:   "三連天秤",
      stat_balanced:     "釣り合い",
      stat_add_beam:     "梁の重さを増やす",
      stat_reduce_beam:  "梁の重さを減らす",
      stat_overload:     "容量超過",
      stat_at_zero:      "ゼロ",
      tag_overload:      "過負荷",
      nar_intro:         "三連天秤シミュレーション。天秤は少しゼロからずれて始まります。秤量前にゼロ調整スライダーで指針を中心に合わせてください。質量追加ボタンで試料を置き、大きい梁から小さい梁の順におもりをずらして指針がゼロに合うまで調整します。準備ができたら回答を送信してください。",
      nar_balanced:      "天秤は水平です。梁の設定: {beam} グラム。試料質量の読み: {sample} グラム。",
      nar_pan_heavy:     "皿が重いです。梁の重さを増やしてください。",
      nar_beams_heavy:   "梁が重いです。梁の重さを減らしてください。",
      nar_mass_placed:   "質量が皿に置かれました。大きい方から小さい方へおもりを動かして釣り合いを見つけ、回答を送信してください。",
      nar_att_placed:    "{mass} kg の付属品が皿に置かれました。大きい方から小さい方へおもりを動かして釣り合いを見つけてください。",
      nar_container_added:"容器が皿に置かれました。質量は {mass} g です。風袋スライダーで容器の重さを相殺し、試料を加えてください。",
      nar_sample_removed:"試料が皿から取り除かれました。",
      nar_sample_removed_cont:"試料が取り除かれました。容器はまだ皿の上にあります。",
      nar_reset:         "天秤がリセットされました。ゼロ調整スライダーで指針を中心に合わせ、試料を置いてください。",
      nar_zeroed:        "現在の梁設定で天秤がゼロに調整されました。",
      nar_att1_on:       "1 キログラムの付属品が梁の端に掛けられました。梁側で皿に最大 1000 グラム多く釣り合わせられます。",
      nar_att1_off:      "1 キログラムの付属品が取り外されました。",
      nar_att5_on:       "500 グラムの付属品が梁の端に掛けられました。梁側で皿に最大 500 グラム多く釣り合わせられます。",
      nar_att5_off:      "500 グラムの付属品が取り外されました。",
      nar_correct:       "正解!質量 = {mass} g",
      nar_incorrect:     "あなたの読み: {reading} g 。実際の質量: {correct} g",
      nar_lang_changed:  "言語が日本語に変更されました。",
      info_title:        "三連天秤",
      info_text:         "容量: 610 g(基本)• 感度/読取性: 0.1 g • 梁: 中央 500g×100g • 後部 100g×10g • 前部 10g×0.1g • 風袋最大 225 g。<br><strong>秤量方法:</strong> 試料を置き、大きい梁から小さい梁の順におもりを動かし指針が 0 に合うまで調整します。試料を加える前に <strong>風袋</strong> スライダーで容器の重さを相殺してください。秤量前に <strong>ゼロ調整</strong> でわずかなずれを補正します。",
      copyright:         "© Taha Mzoughi (2026)"
    }
  },

  /* ============================== RUSSIAN ============================== */
  ru: {
    name: "Русский",
    dir:  "ltr",
    unit: " г",
    t: {
      btn_lm_off:        "СВЕТЛЫЙ РЕЖИМ",
      btn_lm_on:         "СВЕТЛЫЙ РЕЖИМ: ВКЛ",
      btn_nr_on:         "ОЗВУЧКА: ВКЛ",
      btn_nr_off:        "ОЗВУЧКА: ВЫКЛ",
      btn_hc:            "ВЫСОКИЙ КОНТРАСТ",
      btn_fs_normal:     "РАЗМЕР ШРИФТА: НОРМ.",
      btn_fs_lg:         "РАЗМЕР ШРИФТА: БОЛЬШ.",
      btn_fs_xl:         "РАЗМЕР ШРИФТА: XL",
      lang_label:        "Язык:",
      toolbar_label:     "Параметры отображения",
      svg_title:         "Трёхрычажные весы",
      stage_label:       "Симуляция трёхрычажных весов",
      tare_beam_label:   "тара 225г",
      rear_beam_label:   "задн. 100г",
      front_beam_label:  "перед. 10г",
      ctr_beam_label:    "ц. 500г",
      zero_lbl:          "ноль",
      att_lbl:           "доп.",
      lbl_pan:           "Чаша:",
      lbl_attachments:   "Дополнения:",
      lbl_ctr_beam:      "▶ Центр 500г:",
      lbl_rear_beam:     "▶ Задний 100г:",
      lbl_front_beam:    "▶ Передний 10г:",
      lbl_tare_beam:     "▶ Тара 225г:",
      lbl_zero_adj:      "▶ Регулировка нуля:",
      lbl_beam_setting:  "Настройка рычагов:",
      lbl_sample_mass:   "Масса образца:",
      lbl_ready:         "Готово?",
      btn_add_mass:      "Добавить массу",
      btn_add_container: "Добавить контейнер",
      btn_mass_1kg:      "Доп. масса 1 кг",
      btn_mass_500g:     "Доп. масса 500 г",
      btn_remove_mass:   "Убрать массу",
      btn_reset_all:     "Сбросить всё",
      btn_att_1kg:       "Доп. 1 кг (ползунок: 295 г)",
      btn_att_500g:      "Доп. 500 г (ползунок: 147,5 г)",
      btn_rezero:        "Сброс на ноль",
      btn_submit:        "Отправить ответ",
      aria_add_mass:      "Поместить массу на чашу",
      aria_add_container: "Поместить случайный контейнер на чашу",
      aria_mass_1kg:      "Поместить дополнение 1 кг на чашу",
      aria_mass_500g:     "Поместить дополнение 500 г на чашу",
      aria_remove_mass:   "Убрать массу образца с чаши",
      aria_reset:         "Сбросить весы в исходное состояние",
      aria_att1:          "Включить/выключить дополнение 1 килограмм",
      aria_att5:          "Включить/выключить дополнение 500 грамм",
      aria_ctr_slider:    "Ползунок центрального рычага, от 0 до 500 грамм с шагом 100 грамм",
      aria_rear_slider:   "Ползунок заднего рычага, от 0 до 100 грамм с шагом 10 грамм",
      aria_front_slider:  "Ползунок переднего рычага, от 0 до 10 грамм с шагом 0,1 грамма",
      aria_tare_slider:   "Рычаг тары, от 0 до 225 грамм. Компенсирует вес контейнера.",
      aria_zero_slider:   "Ручка регулировки нуля, точная коррекция баланса",
      aria_rezero:        "Установить нуль весов при текущих настройках рычагов",
      aria_submit:        "Отправить измерение и показать правильный ответ",
      aria_beam_setting:  "Текущая настройка рычагов",
      aria_sample_mass:   "Вычисленная масса образца",
      aria_balance_img:   "Трёхрычажные весы",
      stat_balanced:     "СБАЛАНСИРОВАНО",
      stat_add_beam:     "увеличить вес рычагов",
      stat_reduce_beam:  "уменьшить вес рычагов",
      stat_overload:     "превышение ёмкости",
      stat_at_zero:      "на нуле",
      tag_overload:      "ПЕРЕГРУЗКА",
      nar_intro:         "Симуляция трёхрычажных весов. Весы начинают слегка отклонёнными от нуля. Используйте ползунок регулировки нуля, чтобы установить указатель по центру перед взвешиванием. Поместите образец кнопкой Добавить массу, затем перемещайте ползунки от большего рычага к меньшему, пока указатель не совпадёт с нулём. Отправьте ответ, когда будете готовы.",
      nar_balanced:      "Весы сбалансированы. Настройка рычагов: {beam} грамм. Показание массы образца: {sample} грамм.",
      nar_pan_heavy:     "Чаша тяжёлая. Увеличьте вес рычагов.",
      nar_beams_heavy:   "Рычаги тяжёлые. Уменьшите вес рычагов.",
      nar_mass_placed:   "Масса помещена на чашу. Настройте ползунки от большего к меньшему, чтобы найти баланс, затем отправьте ответ.",
      nar_att_placed:    "Дополнение {mass} кг помещено на чашу. Настройте ползунки от большего к меньшему, чтобы найти баланс.",
      nar_container_added:"Контейнер помещён на чашу. Его масса {mass} г. Используйте ползунок тары, чтобы компенсировать вес контейнера, затем добавьте образец.",
      nar_sample_removed:"Образец убран с чаши.",
      nar_sample_removed_cont:"Образец убран. Контейнер всё ещё на чаше.",
      nar_reset:         "Весы сброшены. Используйте ползунок регулировки нуля, чтобы установить указатель по центру, затем поместите образец.",
      nar_zeroed:        "Весы установлены на нуль при текущих настройках рычагов.",
      nar_att1_on:       "Дополнение 1 килограмм повешено на конце рычага. Сторона рычагов теперь уравновешивает до 1000 грамм больше на чаше.",
      nar_att1_off:      "Дополнение 1 килограмм снято.",
      nar_att5_on:       "Дополнение 500 грамм повешено на конце рычага. Сторона рычагов теперь уравновешивает до 500 грамм больше на чаше.",
      nar_att5_off:      "Дополнение 500 грамм снято.",
      nar_correct:       "Верно! Масса = {mass} г",
      nar_incorrect:     "Ваше показание: {reading} г. Фактическая масса: {correct} г",
      nar_lang_changed:  "Язык изменён на русский.",
      info_title:        "Трёхрычажные весы",
      info_text:         "Ёмкость: 610 г (база) • Чувствительность/точность: 0,1 г • Рычаги: Центр 500г×100г • Задний 100г×10г • Передний 10г×0,1г • Тара до 225 г.<br><strong>Для взвешивания:</strong> поместите образец, затем перемещайте ползунки от большего к меньшему рычагу, пока указатель не окажется на 0. Используйте ползунок <strong>Тара</strong>, чтобы компенсировать вес контейнера перед добавлением образца. Используйте <strong>Регулировку нуля</strong> для коррекции небольшого отклонения нуля перед взвешиванием.",
      copyright:         "© Taha Mzoughi (2026)"
    }
  },

  /* ============================== ITALIAN ============================== */
  it: {
    name: "Italiano",
    dir:  "ltr",
    unit: " g",
    t: {
      btn_lm_off:        "MODALITÀ CHIARA",
      btn_lm_on:         "MODALITÀ CHIARA: ON",
      btn_nr_on:         "NARRAZIONE: ATTIVA",
      btn_nr_off:        "NARRAZIONE: DISATTIVA",
      btn_hc:            "ALTO CONTRASTO",
      btn_fs_normal:     "DIMENSIONE FONT: NORMALE",
      btn_fs_lg:         "DIMENSIONE FONT: GRANDE",
      btn_fs_xl:         "DIMENSIONE FONT: XL",
      lang_label:        "Lingua:",
      toolbar_label:     "Opzioni di visualizzazione",
      svg_title:         "Bilancia a tre bracci",
      stage_label:       "Simulazione di bilancia a tre bracci",
      tare_beam_label:   "tara 225g",
      rear_beam_label:   "post. 100g",
      front_beam_label:  "ant. 10g",
      ctr_beam_label:    "centr. 500g",
      zero_lbl:          "zero",
      att_lbl:           "agg.",
      lbl_pan:           "Piatto:",
      lbl_attachments:   "Aggiunte:",
      lbl_ctr_beam:      "▶ Centro 500g:",
      lbl_rear_beam:     "▶ Posteriore 100g:",
      lbl_front_beam:    "▶ Anteriore 10g:",
      lbl_tare_beam:     "▶ Tara 225g:",
      lbl_zero_adj:      "▶ Regol. zero:",
      lbl_beam_setting:  "Lettura bracci:",
      lbl_sample_mass:   "Massa campione:",
      lbl_ready:         "Pronto?",
      btn_add_mass:      "Aggiungi massa",
      btn_add_container: "Aggiungi contenitore",
      btn_mass_1kg:      "Massa 1 kg agg.",
      btn_mass_500g:     "Massa 500g agg.",
      btn_remove_mass:   "Rimuovi massa",
      btn_reset_all:     "Reimposta tutto",
      btn_att_1kg:       "Agg. 1 kg (cursore: 295 g)",
      btn_att_500g:      "Agg. 500 g (cursore: 147,5 g)",
      btn_rezero:        "Ri-azzera",
      btn_submit:        "Invia risposta",
      aria_add_mass:      "Posiziona la massa sul piatto",
      aria_add_container: "Posiziona un contenitore casuale sul piatto",
      aria_mass_1kg:      "Posiziona un'aggiunta da 1 kg sul piatto",
      aria_mass_500g:     "Posiziona un'aggiunta da 500 g sul piatto",
      aria_remove_mass:   "Rimuovi la massa campione dal piatto",
      aria_reset:         "Reimposta la bilancia allo stato iniziale",
      aria_att1:          "Attiva/disattiva aggiunta da 1 chilogrammo",
      aria_att5:          "Attiva/disattiva aggiunta da 500 grammi",
      aria_ctr_slider:    "Cursore braccio centrale, da 0 a 500 grammi a passi di 100 grammi",
      aria_rear_slider:   "Cursore braccio posteriore, da 0 a 100 grammi a passi di 10 grammi",
      aria_front_slider:  "Cursore braccio anteriore, da 0 a 10 grammi a passi di 0,1 grammo",
      aria_tare_slider:   "Braccio tara, da 0 a 225 grammi. Annulla il peso del contenitore.",
      aria_zero_slider:   "Manopola di regolazione zero, correzione fine dell'equilibrio",
      aria_rezero:        "Ri-azzera la bilancia con le impostazioni correnti dei bracci",
      aria_submit:        "Invia la misurazione e rivela la risposta corretta",
      aria_beam_setting:  "Impostazione corrente dei bracci",
      aria_sample_mass:   "Massa calcolata del campione",
      aria_balance_img:   "Bilancia a tre bracci",
      stat_balanced:     "IN EQUILIBRIO",
      stat_add_beam:     "aggiungi peso ai bracci",
      stat_reduce_beam:  "riduci peso dei bracci",
      stat_overload:     "capacità superata",
      stat_at_zero:      "a zero",
      tag_overload:      "SOVRACCARICO",
      nar_intro:         "Simulazione di bilancia a tre bracci. La bilancia inizia leggermente fuori zero. Usa il cursore di regolazione zero per centrare il puntatore prima di pesare. Posiziona un campione con il pulsante Aggiungi massa, poi sposta i cursori dal braccio più grande al più piccolo finché il puntatore non si allinea allo zero. Invia la tua risposta quando sei pronto.",
      nar_balanced:      "Bilancia in equilibrio. Impostazione bracci: {beam} grammi. Lettura massa campione: {sample} grammi.",
      nar_pan_heavy:     "Il piatto è pesante. Aggiungi peso ai bracci.",
      nar_beams_heavy:   "I bracci sono pesanti. Riduci il peso dei bracci.",
      nar_mass_placed:   "Massa posizionata sul piatto. Regola i cursori dal più grande al più piccolo per trovare l'equilibrio, poi invia la risposta.",
      nar_att_placed:    "L'aggiunta da {mass} kg è stata posizionata sul piatto. Regola i cursori dal più grande al più piccolo per trovare l'equilibrio.",
      nar_container_added:"Contenitore posizionato sul piatto. La sua massa è {mass} g. Usa il cursore della tara per annullare il peso del contenitore, poi aggiungi un campione.",
      nar_sample_removed:"Campione rimosso dal piatto.",
      nar_sample_removed_cont:"Campione rimosso. Il contenitore è ancora sul piatto.",
      nar_reset:         "Bilancia reimpostata. Usa il cursore di regolazione zero per centrare il puntatore, poi posiziona un campione.",
      nar_zeroed:        "Bilancia azzerata alle impostazioni correnti dei bracci.",
      nar_att1_on:       "Aggiunta da 1 chilogrammo agganciata all'estremità del braccio. Il lato dei bracci ora bilancia fino a 1000 grammi in più sul piatto.",
      nar_att1_off:      "Aggiunta da 1 chilogrammo rimossa.",
      nar_att5_on:       "Aggiunta da 500 grammi agganciata all'estremità del braccio. Il lato dei bracci ora bilancia fino a 500 grammi in più sul piatto.",
      nar_att5_off:      "Aggiunta da 500 grammi rimossa.",
      nar_correct:       "Corretto! Massa = {mass} g",
      nar_incorrect:     "La tua lettura: {reading} g. Massa effettiva: {correct} g",
      nar_lang_changed:  "Lingua cambiata in italiano.",
      info_title:        "Bilancia a tre bracci",
      info_text:         "Capacità: 610 g (base) • Sensibilità/Leggibilità: 0,1 g • Bracci: Centro 500g×100g • Posteriore 100g×10g • Anteriore 10g×0,1g • Tara fino a 225 g.<br><strong>Per pesare:</strong> posiziona un campione, poi sposta i cursori dal braccio più grande al più piccolo finché il puntatore non si centra su 0. Usa il cursore <strong>Tara</strong> per annullare il peso di un contenitore prima di aggiungere un campione. Usa <strong>Regol. zero</strong> per correggere un leggero scarto dallo zero prima di pesare.",
      copyright:         "© Taha Mzoughi (2026)"
    }
  },

  /* ============================== PORTUGUESE ============================== */
  pt: {
    name: "Português",
    dir:  "ltr",
    unit: " g",
    t: {
      btn_lm_off:        "MODO CLARO",
      btn_lm_on:         "MODO CLARO: LIGADO",
      btn_nr_on:         "NARRAÇÃO: LIGADA",
      btn_nr_off:        "NARRAÇÃO: DESLIGADA",
      btn_hc:            "ALTO CONTRASTE",
      btn_fs_normal:     "TAMANHO FONTE: NORMAL",
      btn_fs_lg:         "TAMANHO FONTE: GRANDE",
      btn_fs_xl:         "TAMANHO FONTE: XL",
      lang_label:        "Idioma:",
      toolbar_label:     "Opções de exibição",
      svg_title:         "Balança de três braços",
      stage_label:       "Simulação de balança de três braços",
      tare_beam_label:   "tara 225g",
      rear_beam_label:   "tras. 100g",
      front_beam_label:  "dia. 10g",
      ctr_beam_label:    "ctr 500g",
      zero_lbl:          "zero",
      att_lbl:           "acess.",
      lbl_pan:           "Prato:",
      lbl_attachments:   "Acessórios:",
      lbl_ctr_beam:      "▶ Centro 500g:",
      lbl_rear_beam:     "▶ Traseiro 100g:",
      lbl_front_beam:    "▶ Dianteiro 10g:",
      lbl_tare_beam:     "▶ Tara 225g:",
      lbl_zero_adj:      "▶ Ajuste zero:",
      lbl_beam_setting:  "Leitura braços:",
      lbl_sample_mass:   "Massa da amostra:",
      lbl_ready:         "Pronto?",
      btn_add_mass:      "Adicionar massa",
      btn_add_container: "Adicionar recipiente",
      btn_mass_1kg:      "Massa 1 kg acessório",
      btn_mass_500g:     "Massa 500 g acessório",
      btn_remove_mass:   "Remover massa",
      btn_reset_all:     "Redefinir tudo",
      btn_att_1kg:       "Acess. 1 kg (cursor: 295 g)",
      btn_att_500g:      "Acess. 500 g (cursor: 147,5 g)",
      btn_rezero:        "Re-zerar",
      btn_submit:        "Enviar resposta",
      aria_add_mass:      "Colocar a massa no prato",
      aria_add_container: "Colocar um recipiente aleatório no prato",
      aria_mass_1kg:      "Colocar um acessório de 1 kg no prato",
      aria_mass_500g:     "Colocar um acessório de 500 g no prato",
      aria_remove_mass:   "Remover a massa da amostra do prato",
      aria_reset:         "Redefinir a balança ao estado inicial",
      aria_att1:          "Alternar acessório de 1 quilograma",
      aria_att5:          "Alternar acessório de 500 gramas",
      aria_ctr_slider:    "Cursor do braço central, de 0 a 500 gramas em passos de 100 gramas",
      aria_rear_slider:   "Cursor do braço traseiro, de 0 a 100 gramas em passos de 10 gramas",
      aria_front_slider:  "Cursor do braço dianteiro, de 0 a 10 gramas em passos de 0,1 grama",
      aria_tare_slider:   "Braço de tara, de 0 a 225 gramas. Cancela o peso do recipiente.",
      aria_zero_slider:   "Botão de ajuste zero, correção fina do equilíbrio",
      aria_rezero:        "Re-zerar a balança nas configurações atuais dos braços",
      aria_submit:        "Enviar sua medição e revelar a resposta correta",
      aria_beam_setting:  "Configuração atual dos braços",
      aria_sample_mass:   "Massa calculada da amostra",
      aria_balance_img:   "Balança de três braços",
      stat_balanced:     "EQUILIBRADA",
      stat_add_beam:     "aumentar peso dos braços",
      stat_reduce_beam:  "reduzir peso dos braços",
      stat_overload:     "capacidade excedida",
      stat_at_zero:      "no zero",
      tag_overload:      "SOBRECARGA",
      nar_intro:         "Simulação de balança de três braços. A balança começa ligeiramente fora do zero. Use o cursor de ajuste zero para centrar o ponteiro antes de pesar. Coloque uma amostra usando o botão Adicionar massa, depois deslize os cursores do maior braço para o menor até que o ponteiro se alinhe ao zero. Envie sua resposta quando estiver pronto.",
      nar_balanced:      "Balança equilibrada. Configuração braços: {beam} gramas. Leitura da massa da amostra: {sample} gramas.",
      nar_pan_heavy:     "O prato está pesado. Adicione mais peso aos braços.",
      nar_beams_heavy:   "Os braços estão pesados. Reduza o peso dos braços.",
      nar_mass_placed:   "Massa colocada no prato. Ajuste os cursores do maior ao menor para encontrar o equilíbrio, depois envie sua resposta.",
      nar_att_placed:    "O acessório de {mass} kg foi colocado no prato. Ajuste os cursores do maior ao menor para encontrar o equilíbrio.",
      nar_container_added:"Recipiente colocado no prato. Sua massa é {mass} g. Use o cursor da tara para cancelar o peso do recipiente, depois adicione uma amostra.",
      nar_sample_removed:"Amostra removida do prato.",
      nar_sample_removed_cont:"Amostra removida. O recipiente ainda está no prato.",
      nar_reset:         "Balança redefinida. Use o cursor de ajuste zero para centrar o ponteiro, depois coloque uma amostra.",
      nar_zeroed:        "Balança zerada nas configurações atuais dos braços.",
      nar_att1_on:       "Acessório de 1 quilograma pendurado na extremidade do braço. O lado dos braços agora contrabalança até 1000 gramas a mais no prato.",
      nar_att1_off:      "Acessório de 1 quilograma removido.",
      nar_att5_on:       "Acessório de 500 gramas pendurado na extremidade do braço. O lado dos braços agora contrabalança até 500 gramas a mais no prato.",
      nar_att5_off:      "Acessório de 500 gramas removido.",
      nar_correct:       "Correto! Massa = {mass} g",
      nar_incorrect:     "Sua leitura: {reading} g. Massa real: {correct} g",
      nar_lang_changed:  "Idioma alterado para português.",
      info_title:        "Balança de três braços",
      info_text:         "Capacidade: 610 g (base) • Sensibilidade/Legibilidade: 0,1 g • Braços: Centro 500g×100g • Traseiro 100g×10g • Dianteiro 10g×0,1g • Tara até 225 g.<br><strong>Para pesar:</strong> coloque uma amostra, depois deslize os cursores do maior braço para o menor até que o ponteiro se centre em 0. Use o cursor <strong>Tara</strong> para cancelar o peso de um recipiente antes de adicionar uma amostra. Use <strong>Ajuste zero</strong> para corrigir um pequeno desvio do zero antes de pesar.",
      copyright:         "© Taha Mzoughi (2026)"
    }
  }
};

/* ════════════════════════════════════════════════════════════
   tbbI18n3932 -- runtime helper: detect language, switch
   languages, translate strings, fill placeholders.
   ════════════════════════════════════════════════════════════ */
var tbbI18n3932 = (function(){
  var current = "en";

  /* Detect the best-matching language for the browser */
  function detect() {
    var langs = [];
    if (navigator.languages && navigator.languages.length) {
      langs = navigator.languages;
    } else if (navigator.language) {
      langs = [navigator.language];
    } else if (navigator.userLanguage) {
      langs = [navigator.userLanguage];
    }
    for (var i = 0; i < langs.length; i++) {
      var code = (langs[i] || "").toLowerCase();
      /* Exact match (e.g. "fr") */
      if (tbbLang3932[code]) return code;
      /* Prefix match (e.g. "fr-CA" -> "fr") */
      var base = code.split("-")[0];
      if (tbbLang3932[base]) return base;
    }
    return "en";
  }

  /* Translate a key with optional placeholder substitution.
     Falls back to English if a key is missing. */
  function tr(key, vars) {
    var pack = tbbLang3932[current] || tbbLang3932.en;
    var s = (pack.t && pack.t[key]) || (tbbLang3932.en.t[key]) || key;
    if (vars) {
      for (var k in vars) {
        if (vars.hasOwnProperty(k)) {
          s = s.split("{" + k + "}").join(vars[k]);
        }
      }
    }
    return s;
  }

  function getUnit() {
    return (tbbLang3932[current] || tbbLang3932.en).unit;
  }
  function getDir() {
    return (tbbLang3932[current] || tbbLang3932.en).dir;
  }
  function getCurrent() { return current; }
  function setCurrent(code) {
    if (tbbLang3932[code]) current = code;
  }

  /* List of {code, name, dir} for building the language dropdown */
  function list() {
    var out = [];
    for (var code in tbbLang3932) {
      if (tbbLang3932.hasOwnProperty(code)) {
        out.push({
          code: code,
          name: tbbLang3932[code].name,
          dir:  tbbLang3932[code].dir
        });
      }
    }
    return out;
  }

  return {
    detect:     detect,
    tr:         tr,
    getUnit:    getUnit,
    getDir:     getDir,
    getCurrent: getCurrent,
    setCurrent: setCurrent,
    list:       list
  };
})();
